### ISSUE TITLE
integrate ical subscription to events

### ISSUE THREAD

**Issue by mikeritter** [churchthemes/church-theme-content#10]
our current solution lets us import and ical feed from our reservation system into our events CPT.

automates things for the volunteers.

any thoughts on integrating this?

**Comment by stevengliebe** [comment]
Hi Mike,

What is your current solution?

Importing into events is ideal. We've had iCal and Google Calendar requests for events. These are not likely things we will build directly into the Church Theme Content plugin but instead would like to offer them as add-ons similar to how we're offering the Custom Recurring Events add-on (we may actually end up having just one "Extras" add-on instead of multiple, to make things easier to manage for users and to provide more value).

This is the plan we're looking at but you are free to develop a plugin to handle iCal imports to meet your needs as a separate project.

**Comment by mikeritter** [comment]
https://wordpress.org/plugins/all-in-one-event-calendar/

**Comment by stevengliebe** [comment]
Thanks Mike. Their plugin is definitely more sophisticated. It should run okay alongside Church Theme Content (we haven't had reports of conflicts, though styles might not match perfectly depending on the theme you are using) if you want to use it instead of our plugin's event features. Their plugin has some import features that no other events plugin for WordPress has.

**Comment by mikeritter** [comment]
yeah. Just need to do a drastic style overhaul if I'm sticking with it. Was hoping to use your events manager for consistency. Thanks for the response.

**Comment by stevengliebe** [comment]
You're welcome. Let me know if you have any other feature requests.
