### ISSUE TITLE
newsletter CPT

### ISSUE THREAD

**Issue by mikeritter** [churchthemes/church-theme-content#11]
I'm looking at building a CPT for our monthly newsletter.

We build and send it out via constantcontact.

Debating the best integration still.

Any interest in adding this feature?

**Comment by stevengliebe** [comment]
Are you wanting to create an archive of newsletters?

This is not a post type I would add to CTC since it's not a very church-specific feature. It might make a good general plugin for all types of sites.

I've seen a few churches use their blog or a regular page for this sort of thing. The simplest approach is to link out to the archive the mailing list service provides.
