### ISSUE TITLE
/wp/v2/ctc_sermon does not include information about video, audio and pdf

### ISSUE THREAD

**Issue by blitt001** [churchthemes/church-theme-content#26]
Currently we want to build a small script in order to upload our sermons from the last 10 years to our wordpress site where this plugin (the pro) is running.

What we have detected is that the response from GET /wp/v2/ctc_sermon do not include the information about the video, audio and pdf that is defined as part of the sermon.

'_ctc_sermon_has_full_text', '_ctc_sermon_video',  '_ctc_sermon_audio', and '_ctc_sermon_pdf', is missing.

**Comment by stevengliebe** [comment]
The plugin only sets the post type as available in the API during registration. There is nothing extra added to support custom fields and we do not currently have plans to add this. You might consider writing plugin to handle that aspect (consider working on this plugin and opening a pull request): https://www.gavick.com/blog/adding-custom-fields-in-the-wordpress-rest-api

Another (possibly easier) approach is to try importing in CSV format with a plugin like https://www.wpallimport.com.

Or since you're already planning to write code (assuming PHP) then you could also look at using native WordPress functions in a plugin like ```wp_insert_post```: https://developer.wordpress.org/reference/functions/wp_insert_post/. Take a look at the code in [migrate-risen.php](https://github.com/churchthemes/church-theme-content/blob/master/includes/admin/migrate-risen.php) to see how we've helped users of one of our old non-Church Content themes move their sermons over.

*PS. Our in-progress [WP Sermons](https://wpsermons.com) plugin will have a variety of options for converting and importing sermon data. It won't be ready in time for your current project but something to keep an eye on for the future.* 😃

**Comment by blitt001** [comment]
In the meantime I have created a file that can be used by WordPress to import the sermons. With success. So now we have our archive up and running starting from 2013..

Looking forward to the WP Sermons plugin.

Thanks for the info

**Comment by stevengliebe** [comment]
That is great to hear. Thanks for keeping an eye on WP Sermons.
